-- GENERATED by infra/seed_fixtures.py — do not edit by hand.
-- Seeds packages whose checksums + archive URLs match real tarballs uploaded
-- to the dev MinIO (http://localhost:9000/nav-packages). Regenerate with:
--   python3 infra/seed_fixtures.py
-- Each package_versions.manifest holds the IndexVersion JSON the CLI consumes
-- via /api/v1/index/:name.

INSERT INTO users (id, username, email, password_hash, email_verified)
VALUES ('b1000000-0000-4000-8000-000000000001', 'nav_seed', 'seed@nav.local', 'seed_placeholder_hash', TRUE)
ON CONFLICT (username) DO NOTHING;

DELETE FROM packages WHERE name IN ('nav-hal', 'cmsis', 'arm-none-eabi-gcc');

-- ---- nav-hal (library, depends on cmsis) -------------------------------------
INSERT INTO packages (id, namespace, name, description, owner_id, total_downloads)
VALUES ('c1000000-0000-4000-8000-000000000001', 'navrobotec', 'nav-hal',
        'NavHAL hardware abstraction layer', 'b1000000-0000-4000-8000-000000000001', 1280);

INSERT INTO package_versions (package_id, version, description, checksum_sha256, archive_url, manifest, published_by)
VALUES
('c1000000-0000-4000-8000-000000000001', '0.5.0', 'NavHAL 0.5.0',
 '6bab8c0f08fb899c8219866ebbac5159b9289b3a02e6da44f52913cc98993e1e',
 'http://localhost:9000/nav-packages/nav-hal-0.5.0.tar.gz',
 '{"version": "0.5.0", "kind": "library", "downloads": {"source": {"url": "http://localhost:9000/nav-packages/nav-hal-0.5.0.tar.gz", "sha256": "6bab8c0f08fb899c8219866ebbac5159b9289b3a02e6da44f52913cc98993e1e"}}, "dependencies": {"cmsis": "^6.0.0"}}'::jsonb,
 'b1000000-0000-4000-8000-000000000001'),
('c1000000-0000-4000-8000-000000000001', '0.4.2', 'NavHAL 0.4.2',
 'ef3c2f655dc297711b07471a2526e5034e2ca19717e888ae792e5cd2b0b167b2',
 'http://localhost:9000/nav-packages/nav-hal-0.4.2.tar.gz',
 '{"version": "0.4.2", "kind": "library", "downloads": {"source": {"url": "http://localhost:9000/nav-packages/nav-hal-0.4.2.tar.gz", "sha256": "ef3c2f655dc297711b07471a2526e5034e2ca19717e888ae792e5cd2b0b167b2"}}, "dependencies": {"cmsis": "^6.0.0"}}'::jsonb,
 'b1000000-0000-4000-8000-000000000001');

-- ---- cmsis (library, no deps) ------------------------------------------------
INSERT INTO packages (id, namespace, name, description, owner_id, total_downloads)
VALUES ('c1000000-0000-4000-8000-000000000002', 'arm', 'cmsis',
        'ARM CMSIS core headers', 'b1000000-0000-4000-8000-000000000001', 4096);

INSERT INTO package_versions (package_id, version, description, checksum_sha256, archive_url, manifest, published_by)
VALUES
('c1000000-0000-4000-8000-000000000002', '6.0.0', 'CMSIS 6.0.0',
 '0ffaab1da5f0ef814638a4ad55beb10071d0545811314c34597fd905aa46959c',
 'http://localhost:9000/nav-packages/cmsis-6.0.0.tar.gz',
 '{"version": "6.0.0", "kind": "library", "downloads": {"source": {"url": "http://localhost:9000/nav-packages/cmsis-6.0.0.tar.gz", "sha256": "0ffaab1da5f0ef814638a4ad55beb10071d0545811314c34597fd905aa46959c"}}}'::jsonb,
 'b1000000-0000-4000-8000-000000000001'),
('c1000000-0000-4000-8000-000000000002', '6.1.0', 'CMSIS 6.1.0',
 '19525fd82e0183b10cacb7a9739b1289528838a7e2a375a83bd6a2af365f0f0e',
 'http://localhost:9000/nav-packages/cmsis-6.1.0.tar.gz',
 '{"version": "6.1.0", "kind": "library", "downloads": {"source": {"url": "http://localhost:9000/nav-packages/cmsis-6.1.0.tar.gz", "sha256": "19525fd82e0183b10cacb7a9739b1289528838a7e2a375a83bd6a2af365f0f0e"}}}'::jsonb,
 'b1000000-0000-4000-8000-000000000001');

-- ---- arm-none-eabi-gcc (toolchain, multi-platform) --------------------------
INSERT INTO packages (id, namespace, name, description, owner_id, total_downloads)
VALUES ('c1000000-0000-4000-8000-000000000003', 'arm', 'arm-none-eabi-gcc',
        'ARM GNU bare-metal toolchain', 'b1000000-0000-4000-8000-000000000001', 8800);

INSERT INTO package_versions (package_id, version, description, checksum_sha256, archive_url, manifest, published_by)
VALUES
('c1000000-0000-4000-8000-000000000003', '13.2.0', 'Arm GNU Toolchain 13.2',
 '73ae1b656c27b64e02938b46bf6b55cfeb9603966d727b5123b8b03902ee2bd3',
 'http://localhost:9000/nav-packages/arm-none-eabi-gcc-13.2.0-linux_x86_64.tar.xz',
 '{"version": "13.2.0", "kind": "toolchain", "toolchain_binaries": ["arm-none-eabi-gcc", "arm-none-eabi-g++", "arm-none-eabi-objcopy", "arm-none-eabi-size"], "downloads": {"linux_x86_64": {"url": "http://localhost:9000/nav-packages/arm-none-eabi-gcc-13.2.0-linux_x86_64.tar.xz", "sha256": "73ae1b656c27b64e02938b46bf6b55cfeb9603966d727b5123b8b03902ee2bd3"}, "darwin_arm64": {"url": "http://localhost:9000/nav-packages/arm-none-eabi-gcc-13.2.0-darwin_arm64.tar.xz", "sha256": "c40e207d30b3b186995868b7b5388f6145da9d2d3c7b90cb92964bda82777da1"}}}'::jsonb,
 'b1000000-0000-4000-8000-000000000001');
