#include "nav/core/board.hpp"
#include "nav/core/cache.hpp"
#include "nav/core/command.hpp"
#include "nav/core/config.hpp"
#include "nav/core/deps.hpp"
#include "nav/core/libdeps.hpp"
#include "nav/core/lockfile.hpp"
#include "nav/core/navhal.hpp"
#include "nav/core/platform.hpp"
#include "nav/core/provision.hpp"
#include "nav/core/toolchain.hpp"
#include "nav/core/ui.hpp"

#include <algorithm>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>

namespace fs = std::filesystem;

namespace nav::core {

int BuildCommand::run(IExecutionContext& ctx, const std::vector<std::string>& /*args*/) {
    ui::step("Building", "Scanning project space and verifying build definitions...");

    auto root = find_project_root();
    if (!root) {
        ui::error("Build halted! No nav.toml found in this directory or any parent.");
        return 1;
    }
    fs::current_path(*root);

    auto cfg = load_project_config(*root);
    if (!cfg) {
        ui::error("Failed to parse 'nav.toml'.");
        return 1;
    }
    if (cfg->target_board.empty()) {
        ui::error("'nav.toml' has no [target].board entry. Set one (see 'nav board list') and re-run.");
        return 1;
    }

    auto catalog = default_catalog(root);
    auto board = catalog.find(cfg->target_board);
    if (!board) {
        ui::error("Board id '" + cfg->target_board + "' not in catalog. Run 'nav board list' to see available ids.");
        return 1;
    }

    if (!fs::exists("build")) {
        fs::create_directory("build");
        ui::info("Created pristine build workspace sub-node.");
    }

    const fs::path board_cmake = fs::path("build") / "nav-board.cmake";
    if (!write_board_cmake(*board, board_cmake)) {
        ui::error("Failed to write " + board_cmake.string() + ".");
        return 1;
    }
    ui::info("Resolved board: " + board->id + " (" + board->arch + ")");

    // Locked dependencies: emit build/nav-deps.cmake from nav.lock so the
    // generated CMake picks up any cached library include/link inputs and the
    // pinned toolchain compiler. Populating the cache is out of scope here — the
    // registry fetch path has been removed; a git-based fetcher will replace it.
    if (auto lock = load_lockfile(*root / "nav.lock")) {
        const std::string platform = host_platform_key(ctx);
        const fs::path deps_cmake = fs::path("build") / "nav-deps.cmake";
        if (!write_deps_cmake(*lock, cache_root(), platform, board->compiler, deps_cmake)) {
            ui::error("Failed to write " + deps_cmake.string() + ".");
            return 1;
        }
    }

    // Nav library dependencies (nav.toml [dependencies]): resolve the transitive
    // graph (local paths + git clones into the shared cache) and emit
    // build/nav-deps-libs.cmake so the generated CMake add_subdirectory()s and
    // links each library against this project's board context.
    const fs::path libdeps_cmake = fs::path("build") / "nav-deps-libs.cmake";
    // Hooks that must run before NavHAL is added (e.g. -DSUBMODULE so a
    // vector-owning library like vaios takes the SysTick/PendSV handlers).
    const fs::path libdeps_pre_cmake = fs::path("build") / "nav-deps-pre.cmake";
    if (!cfg->dependencies.empty()) {
        std::vector<std::string> direct;
        auto libs = resolve_library_deps(ctx, *root, *cfg, &direct);
        if (!libs) {
            ui::error("Could not resolve library dependencies. See errors above.");
            return 1;
        }
        if (!write_libdeps_cmake(*libs, direct, libdeps_cmake)) {
            ui::error("Failed to write " + libdeps_cmake.string() + ".");
            return 1;
        }

        std::error_code rmec;
        const bool owns_vectors =
            std::any_of(libs->begin(), libs->end(), [](const ResolvedLib& l) { return l.navhal_submodule; });
        if (owns_vectors) {
            std::ofstream pre(libdeps_pre_cmake);
            pre << "# Auto-generated by `nav build`: a dependency owns the CPU vectors.\n"
                << "# Build NavHAL as a submodule so it cedes SysTick/PendSV/SVCall/HardFault.\n"
                << "add_compile_definitions(SUBMODULE)\n";
            ui::info("A dependency owns the CPU vectors — building NavHAL with -DSUBMODULE.");
        } else {
            fs::remove(libdeps_pre_cmake, rmec);
        }
        ui::info("Linked " + std::to_string(libs->size()) + " library dependency(ies).");
    } else {
        // No deps now — clear any stale graph from an earlier build.
        std::error_code rmec;
        fs::remove(libdeps_cmake, rmec);
        fs::remove(libdeps_pre_cmake, rmec);
    }

    // NavHAL's Kconfig (extern/NavHAL/Kconfig) uses relative `source` globs that
    // kconfiglib resolves against $srctree (default: cwd). NavHAL standalone runs
    // cmake from its own root so cwd happens to match; we drive cmake from the
    // project root, so point $srctree at the NavHAL clone explicitly. Child
    // processes (cmake -> kconfig.py) inherit it.
    const fs::path navhal_dir = *root / "extern" / "NavHAL";
    // The project links extern/NavHAL into the shared cache; if that link is
    // missing or dangling (cache cleared, fresh checkout), restore it before
    // configuring rather than failing deep inside cmake.
    if (!fs::exists(navhal_dir)) {
        ui::warning("NavHAL missing at extern/NavHAL — restoring from the shared cache.");
        const fs::path navhal_src = ensure_navhal_cached(ctx, kDefaultNavhalRef);
        if (navhal_src.empty() || !link_navhal(ctx, navhal_src, navhal_dir)) {
            ui::error("Could not restore NavHAL. Check your network connection and retry.");
            return 1;
        }
    }
    if (fs::exists(navhal_dir)) {
#ifdef _WIN32
        ::_putenv_s("srctree", navhal_dir.string().c_str());
#else
        ::setenv("srctree", navhal_dir.string().c_str(), /*overwrite=*/1);
#endif
    }

    // Run cmake quietly (silent=true captures output without streaming it), so a
    // successful build stays terse like a container build. On failure we replay
    // the captured log so the diagnostics aren't lost.
    // Self-heal the board's cross compiler: if it isn't on PATH, install it
    // (package manager or nav's downloader) so a freshly-created project builds
    // without a separate manual toolchain step. No-op once present.
    if (!board->compiler.empty()) {
        ToolchainManager tm;
        ToolRequirement req{board->compiler, board->compiler, true};
        if (!tm.probe_tool(ctx, req).is_found) {
            ui::info("Cross compiler '" + board->compiler + "' not found — installing it.");
            install_tools(ctx, {board->compiler});
        }
    }

    // Windows ships no `make`, so drive cmake through Ninja (provisioned above).
    std::vector<std::string> configure_cmd = {"cmake", "-S", ".", "-B", "build"};
#ifdef _WIN32
    configure_cmd.push_back("-G");
    configure_cmd.push_back("Ninja");
#endif

    ui::step("Configuring", "cmake");
    auto conf_res = ctx.execute(configure_cmd, "", /*silent=*/true);
    if (conf_res.exit_code != 0) {
        std::cerr << conf_res.output << std::endl;
        ui::error("Configure failed.");
        return conf_res.exit_code;
    }

    ui::step("Compiling", "cmake --build");
    auto build_res = ctx.execute({"cmake", "--build", "build", "--parallel"}, "", /*silent=*/true);
    if (build_res.exit_code == 0) {
        ui::success("Build complete. Artifacts in build/");
    } else {
        std::cerr << build_res.output << std::endl;
        ui::error("Build failed.");
    }
    return build_res.exit_code;
}

} // namespace nav::core
