id     = "arduino_uno"
name   = "Arduino Uno (ATmega328P)"
arch   = "avr"
vendor = "atmel"
mcu    = "atmega328p"

[cpu]
compile_flags = [
    "-mmcu=atmega328p",
]
link_flags = [
    "-mmcu=atmega328p",
]

[toolchain]
compiler = "avr-gcc"

[flashing]
tool    = "avrdude"
address = ""

[framework]
default   = "arduino"
supported = ["arduino"]
