id     = "esp32_devkitc"
name   = "Espressif ESP32 DevKitC"
arch   = "xtensa-lx6"
vendor = "espressif"
mcu    = "esp32"

[cpu]
compile_flags = []
link_flags    = []

[toolchain]
compiler = "xtensa-esp32-elf-gcc"

[flashing]
tool    = "esptool.py"
address = "0x1000"

[framework]
default   = "esp-idf"
supported = ["esp-idf", "arduino"]
