#include "nav/core/board.hpp"
#include "nav/core/registry.hpp"

#include <fstream>
#include <sstream>
#include <system_error>

namespace fs = std::filesystem;

namespace nav::core {

std::optional<Board> BoardCatalog::find(const std::string& id) const {
    for (const auto& b : boards_) {
        if (b.id == id) return b;
    }
    return std::nullopt;
}

BoardCatalog default_catalog(const std::optional<fs::path>& /*project_root*/) {
    BoardCatalog cat;
    for (const auto& [id, board] : registry().boards()) {
        cat.add(board);
    }
    return cat;
}

namespace {

void emit_string(std::ostringstream& os, std::string_view name, const std::string& value) {
    os << "set(NAV_BOARD_" << name << " \"" << value << "\")\n";
}

void emit_list(std::ostringstream& os, std::string_view name, const std::vector<std::string>& items) {
    os << "set(NAV_BOARD_" << name;
    for (const auto& item : items) {
        os << " \"" << item << "\"";
    }
    os << ")\n";
}

} // namespace

std::string render_board_cmake(const Board& board) {
    std::ostringstream os;
    os << "# Auto-generated by `nav build` from the board registry. Do not edit.\n";
    os << "# Source: data/boards.json :: " << board.id << "\n\n";
    emit_string(os, "ID",            board.id);
    emit_string(os, "NAME",          board.name);
    emit_string(os, "ARCH",          board.arch);
    emit_string(os, "VENDOR",        board.vendor);
    emit_string(os, "MCU",           board.mcu);
    emit_string(os, "COMPILER",      board.compiler);
    emit_list  (os, "COMPILE_FLAGS", board.compile_flags);
    emit_list  (os, "LINK_FLAGS",    board.link_flags);
    emit_string(os, "FLASH_TOOL",    board.flash_tool);
    emit_string(os, "FLASH_ADDRESS", board.flash_address);
    return os.str();
}

bool write_board_cmake(const Board& board, const fs::path& out_path) {
    std::error_code ec;
    if (out_path.has_parent_path()) {
        fs::create_directories(out_path.parent_path(), ec);
        if (ec) return false;
    }
    std::ofstream f(out_path);
    if (!f) return false;
    f << render_board_cmake(board);
    return f.good();
}

} // namespace nav::core
