#include "nav/core/command.hpp"
#include <iostream>
#include <fstream>
#include <filesystem>

#include "nav/core/ui.hpp"

namespace fs = std::filesystem;

namespace nav::core {

int CreateCommand::run(IExecutionContext& ctx, const std::vector<std::string>& args) {
    ui::print_banner();

    std::string proj_name = "my-project";
    if (!args.empty()) {
        proj_name = args[0];
    }

    ui::step("Scaffolding", "Creating root workspace workspace: " + proj_name);

    // 1. Create nested directory structure
    std::vector<std::string> subdirs = {"extern", "include", "src", "lib", "tests"};
    for (const auto& sub : subdirs) {
        fs::create_directories(proj_name + "/" + sub);
    }
    ui::info("Folder structure created locally.");

    // 2. Generate configuration files
    std::string toml_content = "# Nav Configuration File\n[project]\nname = \"" + proj_name + "\"\nversion = \"0.1.0\"\n\n[target]\narch = \"cortex-m4\"\nvendor = \"stm32\"\nboard = \"nucleo_f401re\"\n\n[build]\nbackend = \"cmake\"\n";
    
    // Official requested default configuration payload
    std::string config_content = R"(
#
# Target Platform Configuration
#
CONFIG_ARCH_CORTEX_M4=y
CONFIG_CMAKE_SYSTEM_PROCESSOR="cortex-m4"
CONFIG_VENDOR_STM32=y
CONFIG_VENDOR="stm32"
CONFIG_BOARD_NUCLEO_F401RE=y
CONFIG_BOARD="nucleo_f401re"
# end of Target Platform Configuration

#
# System & Features Configuration
#
CONFIG_USE_FPU=y
CONFIG_DRV_DMA=y
CONFIG_DRV_CRC=y
CONFIG_DRV_DWT=y
CONFIG_DRV_FPU=y
# end of System & Features Configuration

#
# HAL Drivers Configuration
#
CONFIG_DRV_CLOCK=y
CONFIG_DRV_INTERRUPT=y
CONFIG_DRV_GPIO=y
CONFIG_DRV_TIMER=y
CONFIG_DRV_UART=y
CONFIG_DRV_I2C=y
CONFIG_DRV_SPI=y
CONFIG_DRV_PWM=y
CONFIG_DRV_SDIO=y
CONFIG_DRV_FLASH=y
# end of HAL Drivers Configuration

#
# Build Options
#
CONFIG_TOOLCHAIN_PREFIX="arm-none-eabi-"
# CONFIG_STANDALONE is not set
CONFIG_SAMPLE_NONE=y
CONFIG_SAMPLE=""
# CONFIG_TEST is not set
CONFIG_FLASHER="st-flash"
CONFIG_FLASH_ADDRESS="0x8000000"
# end of Build Options
)";

    std::ofstream toml_file(proj_name + "/nav.toml");
    toml_file << toml_content;
    toml_file.close();

    std::ofstream dot_config(proj_name + "/.config");
    dot_config << config_content;
    dot_config.close();

    // Starter embedded navhal scaffold
    std::string cpp_content = R"(/**
 * @file main.cpp
 * @brief Autogenerated starter file. Ready to Fly with NavHAL!
 */

#define CORTEX_M4
#include "navhal.h"

int main(void) {
    // 1. Bootstrap hardware timers
    systick_init(1000); 

    // 2. Open communication channels
    uart2_init(115200);

    uart2_write("System Up.\r\n");

    while (1) {
        // Main logic loop
    }

    return 0;
}
)";
    std::ofstream cpp_file(proj_name + "/src/main.cpp");
    cpp_file << cpp_content;
    cpp_file.close();

    ui::info("Default config files and starter code populated.");

    // 3. Clone NavHAL into extern
    std::string extern_path = proj_name + "/extern";
    std::string repo_url = "https://github.com/ragnar-vallhala/NavHAL.git";

    ui::step("Cloning", "Pulling dependency: NavHAL Framework");

    // Execute live git clone from remote
    auto result = ctx.execute({"git", "clone", "--depth", "1", "--progress", repo_url, "NavHAL"}, extern_path);
    
    if (result.exit_code == 0) {
         // Remove unwanted samples folder immediately to free up noise
         fs::remove_all(extern_path + "/NavHAL/samples");
         ui::info("Dependencies cleaned (Purged samples).");
         
         ui::success("Complete! '" + proj_name + "' initialized successfully.");
    } else {
         ui::error("Clone sequence collapsed. Traceback dump:");
         std::cerr << result.stdout_output << std::endl;
    }

    return result.exit_code;
}

int BuildCommand::run(IExecutionContext& ctx, const std::vector<std::string>& /*args*/) {
    std::cout << "Executing: build" << std::endl;
    return 0;
}

int UploadCommand::run(IExecutionContext& ctx, const std::vector<std::string>& /*args*/) {
    std::cout << "Executing: upload" << std::endl;
    return 0;
}

int MonitorCommand::run(IExecutionContext& ctx, const std::vector<std::string>& /*args*/) {
    std::cout << "Executing: monitor" << std::endl;
    return 0;
}

int CleanCommand::run(IExecutionContext& ctx, const std::vector<std::string>& /*args*/) {
    std::cout << "Executing: clean" << std::endl;
    return 0;
}

int CheckCommand::run(IExecutionContext& ctx, const std::vector<std::string>& /*args*/) {
    std::cout << "Executing: check" << std::endl;
    return 0;
}

int UpdateCommand::run(IExecutionContext& ctx, const std::vector<std::string>& /*args*/) {
    std::cout << "Executing: update" << std::endl;
    return 0;
}

} // namespace nav::core
