#include "nav/core/toolchain.hpp"
#include "nav/core/command.hpp"
#include <iostream>
#include <fstream>
#include <filesystem>
#include <chrono>
#include <thread>
#include <map>
#include <fcntl.h>
#include <termios.h>
#include <unistd.h>
#include <csignal>
#include <atomic>
#include <filesystem>

#include "nav/core/ui.hpp"

namespace fs = std::filesystem;

static std::atomic<bool> g_running_monitor{true};
void handle_sigint(int /*s*/) {
    g_running_monitor = false;
}

namespace nav::core {

int CreateCommand::run(IExecutionContext& ctx, const std::vector<std::string>& args) {
    ui::print_banner();

    std::string proj_name = "my-project";
    if (!args.empty()) {
        proj_name = args[0];
    }

    ui::step("Scaffolding", "Creating root workspace workspace: " + proj_name);

    // 1. Create nested directory structure
    std::vector<std::string> subdirs = {"extern", "include", "src", "lib", "tests"};
    for (const auto& sub : subdirs) {
        fs::create_directories(proj_name + "/" + sub);
    }
    ui::info("Folder structure created locally.");

    // 2. Generate configuration files
    std::string toml_content = "# Nav Configuration File\n[project]\nname = \"" + proj_name + "\"\nversion = \"0.1.0\"\n\n[target]\narch = \"cortex-m4\"\nvendor = \"stm32\"\nboard = \"nucleo_f401re\"\n\n[build]\nbackend = \"cmake\"\n";
    
    // Official requested default configuration payload
    std::string config_content = R"(
#
# Target Platform Configuration
#
CONFIG_ARCH_CORTEX_M4=y
CONFIG_CMAKE_SYSTEM_PROCESSOR="cortex-m4"
CONFIG_VENDOR_STM32=y
CONFIG_VENDOR="stm32"
CONFIG_BOARD_NUCLEO_F401RE=y
CONFIG_BOARD="nucleo_f401re"
# end of Target Platform Configuration

#
# System & Features Configuration
#
CONFIG_USE_FPU=y
CONFIG_DRV_DMA=y
CONFIG_DRV_CRC=y
CONFIG_DRV_DWT=y
CONFIG_DRV_FPU=y
# end of System & Features Configuration

#
# HAL Drivers Configuration
#
CONFIG_DRV_CLOCK=y
CONFIG_DRV_INTERRUPT=y
CONFIG_DRV_GPIO=y
CONFIG_DRV_TIMER=y
CONFIG_DRV_UART=y
CONFIG_DRV_I2C=y
CONFIG_DRV_SPI=y
CONFIG_DRV_PWM=y
CONFIG_DRV_SDIO=y
CONFIG_DRV_FLASH=y
# end of HAL Drivers Configuration

#
# Build Options
#
CONFIG_TOOLCHAIN_PREFIX="arm-none-eabi-"
# CONFIG_STANDALONE is not set
CONFIG_SAMPLE_NONE=y
CONFIG_SAMPLE=""
# CONFIG_TEST is not set
CONFIG_FLASHER="st-flash"
CONFIG_FLASH_ADDRESS="0x8000000"
# end of Build Options
)";

    std::ofstream toml_file(proj_name + "/nav.toml");
    toml_file << toml_content;
    toml_file.close();

    std::ofstream dot_config(proj_name + "/.config");
    dot_config << config_content;
    dot_config.close();

    // Starter embedded navhal scaffold
    std::string c_content = R"(/**
 * @file main.c
 * @brief Autogenerated starter file. Ready to Fly with NavHAL!
 */

#define CORTEX_M4
#include "navhal.h"

int main(void) {
    // 1. Bootstrap hardware timers
    systick_init(1000); 

    // 2. Open communication channels
    uart2_init(115200);

    uart2_write("System Up.\r\n");

    while (1) {
        // Main logic loop
    }

    return 0;
}
)";
    std::ofstream c_file(proj_name + "/src/main.c");
    c_file << c_content;
    c_file.close();

    ui::info("Default config files and starter code populated.");

    // 2.5 Generate Root CMakeLists.txt
    std::string cmake_content = R"(cmake_minimum_required(VERSION 3.20)
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR cortex-m4)
set(TOOLCHAIN_PREFIX "arm-none-eabi-")
set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_ASM_COMPILER ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_OBJCOPY ${TOOLCHAIN_PREFIX}objcopy)
set(CMAKE_BINARY_SIZE ${TOOLCHAIN_PREFIX}size)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
)" + ("\nproject(" + proj_name + " C CXX ASM)\n\n") + R"(set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

# 1. Sync global configuration to dependency path
if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/.config")
    message(STATUS "[Nav] Locking active configuration context...")
    configure_file(
        "${CMAKE_CURRENT_SOURCE_DIR}/.config" 
        "${CMAKE_CURRENT_SOURCE_DIR}/extern/NavHAL/.config" 
        COPYONLY
    )
else()
    message(WARNING "[Nav] Master '.config' not detected in project root! Utilizing ambient internal repository defaults.")
endif()

# 2. Add NavHAL Dependency Framework
add_subdirectory(extern/NavHAL)

# 3. Inherit Dynamic Target Environment Variables
include("${CMAKE_BINARY_DIR}/config.cmake")

# 4. Declare user application target
add_executable(${PROJECT_NAME} src/main.c)

# 5. Synchronize Compilation ABI Flags (Mandatory for VFP Register Matching)
target_compile_options(${PROJECT_NAME} PRIVATE
  "-mcpu=cortex-m4"
  "-mthumb"
  "-mfloat-abi=hard"
  "-mfpu=fpv4-sp-d16"
)

# 6. Hardware-Bound Linker Directives
target_link_options(${PROJECT_NAME} PRIVATE
  "-T" "${CMAKE_CURRENT_SOURCE_DIR}/extern/NavHAL/src/board/${BOARD}/linker.ld"
  "-nostdlib"
  "--specs=nosys.specs"
  "-mcpu=cortex-m4"
  "-mthumb"
  "-mfloat-abi=hard"
  "-mfpu=fpv4-sp-d16"
)

# 6. Inherit linkage rules (Whole Archive mandatory for static HAL exports)
target_link_libraries(${PROJECT_NAME} PRIVATE
  -Wl,--start-group
    -Wl,--whole-archive hal -Wl,--no-whole-archive
    -lgcc
  -Wl,--end-group
)

# 5. Bind includes
target_include_directories(${PROJECT_NAME} PUBLIC
    include
    extern/NavHAL/include
)

# 6. Flash target support
if(DEFINED FLASHER AND DEFINED FLASH_ADDRESS)
    add_custom_target(flash
      COMMAND ${CMAKE_OBJCOPY} -O binary $<TARGET_FILE:${PROJECT_NAME}> ${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}.bin
      COMMAND ${FLASHER} write ${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}.bin ${FLASH_ADDRESS}
      DEPENDS ${PROJECT_NAME}
      COMMENT "Pumping Binary payload onto board..."
    )
endif()
)";
    
    std::ofstream cmake_file(proj_name + "/CMakeLists.txt");
    cmake_file << cmake_content;
    cmake_file.close();
    ui::info("Root build definitions (CMakeLists.txt) successfully orchestrated.");

    // 3. Clone NavHAL into extern
    std::string extern_path = proj_name + "/extern";
    std::string repo_url = "https://github.com/ragnar-vallhala/NavHAL.git";

    ui::step("Cloning", "Pulling dependency: NavHAL Framework");

    // Execute live git clone from remote
    auto result = ctx.execute({"git", "clone", "--depth", "1", "--branch", "stable", "--progress", repo_url, "NavHAL"}, extern_path);
    
    if (result.exit_code == 0) {
         // Remove unwanted samples folder immediately to free up noise
         fs::remove_all(extern_path + "/NavHAL/samples");
         ui::info("Dependencies cleaned (Purged samples).");
         
         ui::success("Complete! '" + proj_name + "' initialized successfully.");
    } else {
         ui::error("Clone sequence collapsed. Traceback dump:");
         std::cerr << result.stdout_output << std::endl;
    }

    return result.exit_code;
}

int BuildCommand::run(IExecutionContext& ctx, const std::vector<std::string>& /*args*/) {
    ui::step("Building", "Scanning project space and verifying build definitions...");

    // 1. Context Integrity Check
    if (!fs::exists("nav.toml")) {
        ui::error("Build halted! This command must be executed from within a valid project root (Missing nav.toml).");
        return 1;
    }

    // 2. Scaffold Build Node
    if (!fs::exists("build")) {
        fs::create_directory("build");
        ui::info("Created pristine build workspace sub-node.");
    }

    // 3. Configuration Hook (Generate Cache)
    ui::step("Configuring", "Initializing dynamic build system generator (CMake)...");
    auto conf_res = ctx.execute({"cmake", "-S", ".", "-B", "build"});

    if (conf_res.exit_code != 0) {
        ui::error("Configuration sequence failed. Terminating build pipe.");
        return conf_res.exit_code;
    }

    // 4. Actual Compilation Hook
    ui::step("Compiling", "Engaging native system builders...");
    auto build_res = ctx.execute({"cmake", "--build", "build", "--parallel"});

    if (build_res.exit_code == 0) {
        ui::success("Compilation Successful! Binary artifacts successfully established in build/");
    } else {
        ui::error("Builder reported non-recoverable compilation failure.");
    }

    return build_res.exit_code;
}

int UploadCommand::run(IExecutionContext& ctx, const std::vector<std::string>& /*args*/) {
    ui::step("Uploading", "Initializing physical hardware deployment pipeline...");

    // 1. Context Integrity Check
    if (!fs::exists("nav.toml")) {
        ui::error("Upload halted! Command requires an active project context.");
        return 1;
    }

    if (!fs::exists("build")) {
        ui::error("Missing binary context. Please execute 'nav build' prior to upload attempts.");
        return 1;
    }

    // 2. Invoke Orchestrator Flashing Target
    ui::step("Flashing", "Engaging physical hardware link and transmitting payload...");
    
    // Native CMake command triggers automatic dependency builds then fires flasher logic
    auto upload_res = ctx.execute({"cmake", "--build", "build", "--target", "flash"});

    if (upload_res.exit_code == 0) {
        ui::success("Upload Finalized! Targeted hardware reset and broadcasting live firmware.");
    } else {
        ui::error("Hardware Interface Reported Fault! Please verify physical connections and ensure target board power.");
    }

    return upload_res.exit_code;
}

int MonitorCommand::run(IExecutionContext& /*ctx*/, const std::vector<std::string>& args) {
    std::string target_port = "";
    std::string baud_str = "9600";

    // 1. Parse Args
    for (size_t i = 0; i < args.size(); ++i) {
        if ((args[i] == "--port" || args[i] == "-p") && (i + 1 < args.size())) {
            target_port = args[++i];
        } else if ((args[i] == "--baud" || args[i] == "-b") && (i + 1 < args.size())) {
            baud_str = args[++i];
        }
    }

    // 2. Autodetect port
    if (target_port.empty()) {
        ui::step("Scanning", "Autodetecting active serial hardware interfaces...");
        try {
            for (const auto& entry : fs::directory_iterator("/dev")) {
                std::string dev_path = entry.path().string();
                if (dev_path.find("ttyACM") != std::string::npos || dev_path.find("ttyUSB") != std::string::npos) {
                    target_port = dev_path;
                    break;
                }
            }
        } catch (...) {}
    }

    if (target_port.empty()) {
        ui::error("Auto-detection failed. No hardware detected. Specify manually.");
        return 1;
    }

    // 3. Resolve Baud constant
    speed_t baud_rate = B9600; // fallback
    static const std::map<std::string, speed_t> baud_map = {
        {"9600", B9600}, {"19200", B19200}, {"38400", B38400},
        {"57600", B57600}, {"115200", B115200}
    };
    auto it = baud_map.find(baud_str);
    if (it != baud_map.end()) {
        baud_rate = it->second;
    } else {
        ui::warning("Unknown baud requested (" + baud_str + "). Falling back to 9600.");
    }

    // 4. Establish Native Device Link
    ui::step("Monitoring", "Opening direct native pipe: [" + target_port + "] at " + baud_str + " baud...");
    
    int fd = open(target_port.c_str(), O_RDWR | O_NOCTTY | O_SYNC | O_NONBLOCK);
    if (fd < 0) {
        ui::error("Kernel Access Denied! Permission denied or device already locked.");
        return 1;
    }

    // Standard POSIX Termios configuration for raw serial streaming
    struct termios tty;
    if (tcgetattr(fd, &tty) != 0) {
        ui::error("Hardware API Fault: Could not read termios properties.");
        close(fd);
        return 1;
    }

    cfsetospeed(&tty, baud_rate);
    cfsetispeed(&tty, baud_rate);

    tty.c_cflag = (tty.c_cflag & ~CSIZE) | CS8;
    tty.c_iflag &= ~IGNBRK; 
    tty.c_lflag = 0; // purely raw
    tty.c_oflag = 0;
    tty.c_cc[VMIN]  = 0; 
    tty.c_cc[VTIME] = 5; // 0.5 sec read timeout block

    tty.c_iflag &= ~(IXON | IXOFF | IXANY); // disable flow control
    tty.c_cflag |= (CLOCAL | CREAD); // ignore ctrl signals, enable read
    tty.c_cflag &= ~(PARENB | PARODD); // disable parity
    tty.c_cflag &= ~CSTOPB;
    tty.c_cflag &= ~CRTSCTS;

    if (tcsetattr(fd, TCSANOW, &tty) != 0) {
        ui::error("Hardware API Fault: Could not lock target baud configuration.");
        close(fd);
        return 1;
    }

    ui::success("Successfully latched interface. Capturing raw telemetry stream now...");
    ui::info("System notice: [Press Ctrl+C to cleanly detatch]");
    std::cout << "-------------------------------------------------------------\n" << std::endl;

    // 5. Secure SIGINT and Enter Active Listening Ring Loop
    g_running_monitor = true;
    auto old_handler = std::signal(SIGINT, handle_sigint);

    char read_buffer[1024];
    while (g_running_monitor) {
        ssize_t bytes_read = read(fd, read_buffer, sizeof(read_buffer));
        if (bytes_read > 0) {
            std::cout.write(read_buffer, bytes_read);
            std::cout.flush();
        } else if (bytes_read < 0 && errno != EAGAIN && errno != EWOULDBLOCK) {
             // Fatal IO collapse
             ui::error("\nCritical Link Failure: Connection severed by host kernel.");
             break;
        }
        
        // Brief rest to save host CPU cycle spin
        std::this_thread::sleep_for(std::chrono::milliseconds(1));
    }

    // Restore clean state
    std::signal(SIGINT, old_handler);
    close(fd);

    std::cout << "\n\n";
    ui::success("Link detatched gracefully. Channel closed.");
    return 0;
}

int CleanCommand::run(IExecutionContext& /*ctx*/, const std::vector<std::string>& /*args*/) {
    ui::step("Cleaning", "Analyzing intermediate cache status and target binary presence...");

    if (!fs::exists("nav.toml")) {
        ui::error("Cleanup aborted! Please execute command from within a valid project root.");
        return 1;
    }

    if (!fs::exists("build")) {
        ui::info("Workspace structure is already pristine. No 'build/' directory detected.");
        ui::success("System cleanly purged (nothing to do).");
        return 0;
    }

    try {
        ui::info("Purging cached object data and binary artifacts...");
        fs::remove_all("build");
        ui::success("Workspace flushed! Build context successfully reset to defaults.");
    } catch (const std::exception& e) {
        ui::error("Cache purge failed! File handle may be locked by another process.");
        return 1;
    }

    return 0;
}


int CheckCommand::run(IExecutionContext& ctx, const std::vector<std::string>& /*args*/) {
    ToolchainManager tm;
    int failed_critical = 0;

    // ==========================================
    // STAGE 1: System-Wide Health Verify
    // ==========================================
    ui::step("Validating [STAGE 1]", "System Environment Dependencies");
    auto system_reqs = tm.get_system_requirements();
    for (const auto& req : system_reqs) {
        auto res = tm.probe_tool(ctx, req);
        if (res.is_found) {
            std::cout << "  " << ui::GREEN << "✔ " << ui::RESET << ui::BOLD << res.tool_name << ui::RESET << " -> Detected.\n";
        } else {
            if (res.is_critical) { failed_critical++; std::cout << "  " << ui::RED << "✖ " << ui::RESET << ui::BOLD << res.tool_name << ui::RESET << " -> " << ui::RED << "NOT FOUND (CRITICAL)\n" << ui::RESET; }
            else { std::cout << "  " << ui::YELLOW << "⚠ " << ui::RESET << ui::BOLD << res.tool_name << ui::RESET << " -> Optional (Not Installed)\n"; }
        }
    }
    std::cout << std::endl;

    // ==========================================
    // STAGE 2: Contextual Project Dependency Scan
    // ==========================================
    ui::step("Validating [STAGE 2]", "Target Specific Hardware Dependency");
    
    std::string board_id = "";
    std::ifstream toml_file("nav.toml");
    
    if (!toml_file.is_open()) {
        ui::warning("No 'nav.toml' located in current scope. Project checks bypassed.");
    } else {
        std::string line;
        while (std::getline(toml_file, line)) {
            // Very naive basic string parsing for early stage speed
            if (line.find("board =") != std::string::npos) {
                size_t first_quote = line.find("\"");
                size_t last_quote = line.find_last_of("\"");
                if (first_quote != std::string::npos && last_quote != std::string::npos && last_quote > first_quote) {
                    board_id = line.substr(first_quote + 1, last_quote - first_quote - 1);
                    break;
                }
            }
        }
        toml_file.close();

        if (board_id.empty()) {
            ui::warning("Resolved configuration is incomplete. Unable to extract target 'board' from toml.");
        } else {
            ui::info("Context resolved! Targeting hardware configuration: [" + board_id + "]");
            
            auto project_reqs = tm.get_project_requirements(board_id);
            for (const auto& req : project_reqs) {
                auto res = tm.probe_tool(ctx, req);
                if (res.is_found) {
                    std::cout << "  " << ui::GREEN << "✔ " << ui::RESET << ui::BOLD << res.tool_name << ui::RESET << " -> " << res.version_info << std::endl;
                } else {
                    if (res.is_critical) { failed_critical++; std::cout << "  " << ui::RED << "✖ " << ui::RESET << ui::BOLD << res.tool_name << ui::RESET << " -> " << ui::RED << "NOT FOUND (CRITICAL)\n" << ui::RESET; }
                    else { std::cout << "  " << ui::YELLOW << "⚠ " << ui::RESET << ui::BOLD << res.tool_name << ui::RESET << " -> Optional (Not Installed)\n"; }
                }
            }
        }
    }
    
    std::cout << std::endl;

    if (failed_critical > 0) {
        ui::error("Comprehensive assessment complete. Total Critical Defects: " + std::to_string(failed_critical));
        return 1;
    }

    ui::success("All verified verification thresholds passed. System state secure.");
    return 0;
}

int UpdateCommand::run(IExecutionContext& ctx, const std::vector<std::string>& /*args*/) {
    ui::step("Updating", "Synchronizing ecosystem dependencies and validation metrics...");

    // 1. Local Descriptor Check
    if (!fs::exists("nav.toml")) {
        ui::error("Update halted! Command must be executed within project root.");
        return 1;
    }

    // 2. Framework Self-Healing
    if (!fs::exists("extern/NavHAL")) {
        ui::step("Cloning", "Core Dependency 'NavHAL' missing! Pulling secure vector...");
        auto clone_res = ctx.execute({"git", "clone", "--branch", "stable", "--progress", "https://github.com/ragnar-vallhala/NavHAL.git", "extern/NavHAL"});
        
        if (clone_res.exit_code == 0) {
            fs::remove_all("extern/NavHAL/samples");
            ui::success("Successfully tethered NavHAL framework into local workspace.");
        } else {
            ui::error("Network fault! Remote repository fetch failed.");
            return 1;
        }
    } else {
        ui::info("Framework dependency present and secured.");
    }

    // 3. Extract Target Board Profile
    std::string board_id = "";
    std::ifstream toml_file("nav.toml");
    std::string line;
    while (std::getline(toml_file, line)) {
        if (line.find("board") != std::string::npos && line.find("=") != std::string::npos) {
            size_t q1 = line.find('"');
            size_t q2 = line.find('"', q1 + 1);
            if (q1 != std::string::npos && q2 != std::string::npos) {
                board_id = line.substr(q1 + 1, q2 - q1 - 1);
                break;
            }
        }
    }

    // 4. Evaluate Missing Requirements
    ToolchainManager tm;
    std::vector<std::string> missing_bins;

    auto sys_reqs = tm.get_system_requirements();
    for (const auto& req : sys_reqs) {
        if (req.binary_name == "apt" || req.binary_name == "dnf" || req.binary_name == "pacman") continue;
        if (!tm.probe_tool(ctx, req).is_found) { missing_bins.push_back(req.binary_name); }
    }

    if (!board_id.empty()) {
        auto proj_reqs = tm.get_project_requirements(board_id);
        for (const auto& req : proj_reqs) {
             if (!tm.probe_tool(ctx, req).is_found) { missing_bins.push_back(req.binary_name); }
        }
    }

    if (missing_bins.empty()) {
        ui::success("Verification absolute! All local toolchains verified and active.");
        return 0;
    }

    // 5. Adaptive Tool Auto-Installation System
    ui::step("Provisioning", "Autodiscovering package paths for missing system dependencies...");
    
    std::vector<std::string> packages_to_install;
    // Manual Mapping from Binary Name to System Package Names (Debian/Ubuntu)
    for (const auto& bin : missing_bins) {
        if (bin == "cmake") packages_to_install.push_back("cmake");
        else if (bin == "git") packages_to_install.push_back("git");
        else if (bin == "arm-none-eabi-gcc") packages_to_install.push_back("gcc-arm-none-eabi");
        else if (bin == "st-flash") packages_to_install.push_back("stlink-tools");
        else if (bin == "python3") packages_to_install.push_back("python3");
    }

    if (packages_to_install.empty()) {
        ui::warning("Detected unique tooling, but could not resolve canonical system package mappings automatically.");
        return 0;
    }

    std::string installer = "";
    if (fs::exists("/usr/bin/apt")) {
        installer = "apt";
    } else {
        ui::warning("Automatic Provisioning only available on Debian/Ubuntu/Mint systems currently.");
        return 0;
    }

    ui::info("Required system components: " + std::to_string(packages_to_install.size()));
    
    std::vector<std::string> install_cmd = {"sudo", installer, "install", "-y"};
    for(const auto& p : packages_to_install) {
        install_cmd.push_back(p);
    }

    ui::step("Installing", "Invoking system package manager elevation sequence...");
    auto ins_res = ctx.execute(install_cmd);

    if (ins_res.exit_code == 0) {
        ui::success("Environment secured! Total system state synchronized.");
    } else {
        ui::error("Installation execution fault. Please run manually via shell.");
    }

    return ins_res.exit_code;
}

} // namespace nav::core
