#include "nav/core/toolchain.hpp"
#include "nav/core/command.hpp"
#include <iostream>
#include <fstream>
#include <filesystem>

#include "nav/core/ui.hpp"

namespace fs = std::filesystem;

namespace nav::core {

int CreateCommand::run(IExecutionContext& ctx, const std::vector<std::string>& args) {
    ui::print_banner();

    std::string proj_name = "my-project";
    if (!args.empty()) {
        proj_name = args[0];
    }

    ui::step("Scaffolding", "Creating root workspace workspace: " + proj_name);

    // 1. Create nested directory structure
    std::vector<std::string> subdirs = {"extern", "include", "src", "lib", "tests"};
    for (const auto& sub : subdirs) {
        fs::create_directories(proj_name + "/" + sub);
    }
    ui::info("Folder structure created locally.");

    // 2. Generate configuration files
    std::string toml_content = "# Nav Configuration File\n[project]\nname = \"" + proj_name + "\"\nversion = \"0.1.0\"\n\n[target]\narch = \"cortex-m4\"\nvendor = \"stm32\"\nboard = \"nucleo_f401re\"\n\n[build]\nbackend = \"cmake\"\n";
    
    // Official requested default configuration payload
    std::string config_content = R"(
#
# Target Platform Configuration
#
CONFIG_ARCH_CORTEX_M4=y
CONFIG_CMAKE_SYSTEM_PROCESSOR="cortex-m4"
CONFIG_VENDOR_STM32=y
CONFIG_VENDOR="stm32"
CONFIG_BOARD_NUCLEO_F401RE=y
CONFIG_BOARD="nucleo_f401re"
# end of Target Platform Configuration

#
# System & Features Configuration
#
CONFIG_USE_FPU=y
CONFIG_DRV_DMA=y
CONFIG_DRV_CRC=y
CONFIG_DRV_DWT=y
CONFIG_DRV_FPU=y
# end of System & Features Configuration

#
# HAL Drivers Configuration
#
CONFIG_DRV_CLOCK=y
CONFIG_DRV_INTERRUPT=y
CONFIG_DRV_GPIO=y
CONFIG_DRV_TIMER=y
CONFIG_DRV_UART=y
CONFIG_DRV_I2C=y
CONFIG_DRV_SPI=y
CONFIG_DRV_PWM=y
CONFIG_DRV_SDIO=y
CONFIG_DRV_FLASH=y
# end of HAL Drivers Configuration

#
# Build Options
#
CONFIG_TOOLCHAIN_PREFIX="arm-none-eabi-"
# CONFIG_STANDALONE is not set
CONFIG_SAMPLE_NONE=y
CONFIG_SAMPLE=""
# CONFIG_TEST is not set
CONFIG_FLASHER="st-flash"
CONFIG_FLASH_ADDRESS="0x8000000"
# end of Build Options
)";

    std::ofstream toml_file(proj_name + "/nav.toml");
    toml_file << toml_content;
    toml_file.close();

    std::ofstream dot_config(proj_name + "/.config");
    dot_config << config_content;
    dot_config.close();

    // Starter embedded navhal scaffold
    std::string c_content = R"(/**
 * @file main.c
 * @brief Autogenerated starter file. Ready to Fly with NavHAL!
 */

#define CORTEX_M4
#include "navhal.h"

int main(void) {
    // 1. Bootstrap hardware timers
    systick_init(1000); 

    // 2. Open communication channels
    uart2_init(115200);

    uart2_write("System Up.\r\n");

    while (1) {
        // Main logic loop
    }

    return 0;
}
)";
    std::ofstream c_file(proj_name + "/src/main.c");
    c_file << c_content;
    c_file.close();

    ui::info("Default config files and starter code populated.");

    // 2.5 Generate Root CMakeLists.txt
    std::string cmake_content = R"(cmake_minimum_required(VERSION 3.20)
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR cortex-m4)
set(TOOLCHAIN_PREFIX "arm-none-eabi-")
set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_ASM_COMPILER ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_OBJCOPY ${TOOLCHAIN_PREFIX}objcopy)
set(CMAKE_BINARY_SIZE ${TOOLCHAIN_PREFIX}size)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
)" + ("\nproject(" + proj_name + " C CXX ASM)\n\n") + R"(set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

# 1. Sync global configuration to dependency path
message(STATUS "[Nav] Synchronizing configuration state...")
execute_process(
    COMMAND ${CMAKE_COMMAND} -E copy 
    "${CMAKE_CURRENT_SOURCE_DIR}/.config" 
    "${CMAKE_CURRENT_SOURCE_DIR}/extern/NavHAL/.config"
)

# 2. Add NavHAL Dependency Framework
add_subdirectory(extern/NavHAL)

# 3. Inherit Dynamic Target Environment Variables
include("${CMAKE_BINARY_DIR}/config.cmake")

# 4. Declare user application target
add_executable(${PROJECT_NAME} src/main.c)

# 5. Synchronize Compilation ABI Flags (Mandatory for VFP Register Matching)
target_compile_options(${PROJECT_NAME} PRIVATE
  "-mcpu=cortex-m4"
  "-mthumb"
  "-mfloat-abi=hard"
  "-mfpu=fpv4-sp-d16"
)

# 6. Hardware-Bound Linker Directives
target_link_options(${PROJECT_NAME} PRIVATE
  "-T" "${CMAKE_CURRENT_SOURCE_DIR}/extern/NavHAL/src/board/${BOARD}/linker.ld"
  "-nostdlib"
  "--specs=nosys.specs"
  "-mcpu=cortex-m4"
  "-mthumb"
  "-mfloat-abi=hard"
  "-mfpu=fpv4-sp-d16"
)

# 6. Inherit linkage rules (Whole Archive mandatory for static HAL exports)
target_link_libraries(${PROJECT_NAME} PRIVATE
  -Wl,--start-group
    -Wl,--whole-archive hal -Wl,--no-whole-archive
    -lgcc
  -Wl,--end-group
)

# 5. Bind includes
target_include_directories(${PROJECT_NAME} PUBLIC
    include
    extern/NavHAL/include
)

# 6. Flash target support
if(DEFINED FLASHER AND DEFINED FLASH_ADDRESS)
    add_custom_target(flash
      COMMAND ${CMAKE_OBJCOPY} -O binary $<TARGET_FILE:${PROJECT_NAME}> ${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}.bin
      COMMAND ${FLASHER} write ${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}.bin ${FLASH_ADDRESS}
      DEPENDS ${PROJECT_NAME}
      COMMENT "Pumping Binary payload onto board..."
    )
endif()
)";
    
    std::ofstream cmake_file(proj_name + "/CMakeLists.txt");
    cmake_file << cmake_content;
    cmake_file.close();
    ui::info("Root build definitions (CMakeLists.txt) successfully orchestrated.");

    // 3. Clone NavHAL into extern
    std::string extern_path = proj_name + "/extern";
    std::string repo_url = "https://github.com/ragnar-vallhala/NavHAL.git";

    ui::step("Cloning", "Pulling dependency: NavHAL Framework");

    // Execute live git clone from remote
    auto result = ctx.execute({"git", "clone", "--depth", "1", "--progress", repo_url, "NavHAL"}, extern_path);
    
    if (result.exit_code == 0) {
         // Remove unwanted samples folder immediately to free up noise
         fs::remove_all(extern_path + "/NavHAL/samples");
         ui::info("Dependencies cleaned (Purged samples).");
         
         ui::success("Complete! '" + proj_name + "' initialized successfully.");
    } else {
         ui::error("Clone sequence collapsed. Traceback dump:");
         std::cerr << result.stdout_output << std::endl;
    }

    return result.exit_code;
}

int BuildCommand::run(IExecutionContext& ctx, const std::vector<std::string>& /*args*/) {
    ui::step("Building", "Scanning project space and verifying build definitions...");

    // 1. Context Integrity Check
    if (!fs::exists("nav.toml")) {
        ui::error("Build halted! This command must be executed from within a valid project root (Missing nav.toml).");
        return 1;
    }

    // 2. Scaffold Build Node
    if (!fs::exists("build")) {
        fs::create_directory("build");
        ui::info("Created pristine build workspace sub-node.");
    }

    // 3. Configuration Hook (Generate Cache)
    ui::step("Configuring", "Initializing dynamic build system generator (CMake)...");
    auto conf_res = ctx.execute({"cmake", "-S", ".", "-B", "build"});

    if (conf_res.exit_code != 0) {
        ui::error("Configuration sequence failed. Terminating build pipe.");
        return conf_res.exit_code;
    }

    // 4. Actual Compilation Hook
    ui::step("Compiling", "Engaging native system builders...");
    auto build_res = ctx.execute({"cmake", "--build", "build", "--parallel"});

    if (build_res.exit_code == 0) {
        ui::success("Compilation Successful! Binary artifacts successfully established in build/");
    } else {
        ui::error("Builder reported non-recoverable compilation failure.");
    }

    return build_res.exit_code;
}

int UploadCommand::run(IExecutionContext& ctx, const std::vector<std::string>& /*args*/) {
    ui::step("Uploading", "Initializing physical hardware deployment pipeline...");

    // 1. Context Integrity Check
    if (!fs::exists("nav.toml")) {
        ui::error("Upload halted! Command requires an active project context.");
        return 1;
    }

    if (!fs::exists("build")) {
        ui::error("Missing binary context. Please execute 'nav build' prior to upload attempts.");
        return 1;
    }

    // 2. Invoke Orchestrator Flashing Target
    ui::step("Flashing", "Engaging physical hardware link and transmitting payload...");
    
    // Native CMake command triggers automatic dependency builds then fires flasher logic
    auto upload_res = ctx.execute({"cmake", "--build", "build", "--target", "flash"});

    if (upload_res.exit_code == 0) {
        ui::success("Upload Finalized! Targeted hardware reset and broadcasting live firmware.");
    } else {
        ui::error("Hardware Interface Reported Fault! Please verify physical connections and ensure target board power.");
    }

    return upload_res.exit_code;
}

int MonitorCommand::run(IExecutionContext& ctx, const std::vector<std::string>& /*args*/) {
    std::cout << "Executing: monitor" << std::endl;
    return 0;
}

int CleanCommand::run(IExecutionContext& ctx, const std::vector<std::string>& /*args*/) {
    std::cout << "Executing: clean" << std::endl;
    return 0;
}


int CheckCommand::run(IExecutionContext& ctx, const std::vector<std::string>& /*args*/) {
    ToolchainManager tm;
    int failed_critical = 0;

    // ==========================================
    // STAGE 1: System-Wide Health Verify
    // ==========================================
    ui::step("Validating [STAGE 1]", "System Environment Dependencies");
    auto system_reqs = tm.get_system_requirements();
    for (const auto& req : system_reqs) {
        auto res = tm.probe_tool(ctx, req);
        if (res.is_found) {
            std::cout << "  " << ui::GREEN << "✔ " << ui::RESET << ui::BOLD << res.tool_name << ui::RESET << " -> Detected.\n";
        } else {
            if (res.is_critical) { failed_critical++; std::cout << "  " << ui::RED << "✖ " << ui::RESET << ui::BOLD << res.tool_name << ui::RESET << " -> " << ui::RED << "NOT FOUND (CRITICAL)\n" << ui::RESET; }
            else { std::cout << "  " << ui::YELLOW << "⚠ " << ui::RESET << ui::BOLD << res.tool_name << ui::RESET << " -> Optional (Not Installed)\n"; }
        }
    }
    std::cout << std::endl;

    // ==========================================
    // STAGE 2: Contextual Project Dependency Scan
    // ==========================================
    ui::step("Validating [STAGE 2]", "Target Specific Hardware Dependency");
    
    std::string board_id = "";
    std::ifstream toml_file("nav.toml");
    
    if (!toml_file.is_open()) {
        ui::warning("No 'nav.toml' located in current scope. Project checks bypassed.");
    } else {
        std::string line;
        while (std::getline(toml_file, line)) {
            // Very naive basic string parsing for early stage speed
            if (line.find("board =") != std::string::npos) {
                size_t first_quote = line.find("\"");
                size_t last_quote = line.find_last_of("\"");
                if (first_quote != std::string::npos && last_quote != std::string::npos && last_quote > first_quote) {
                    board_id = line.substr(first_quote + 1, last_quote - first_quote - 1);
                    break;
                }
            }
        }
        toml_file.close();

        if (board_id.empty()) {
            ui::warning("Resolved configuration is incomplete. Unable to extract target 'board' from toml.");
        } else {
            ui::info("Context resolved! Targeting hardware configuration: [" + board_id + "]");
            
            auto project_reqs = tm.get_project_requirements(board_id);
            for (const auto& req : project_reqs) {
                auto res = tm.probe_tool(ctx, req);
                if (res.is_found) {
                    std::cout << "  " << ui::GREEN << "✔ " << ui::RESET << ui::BOLD << res.tool_name << ui::RESET << " -> " << res.version_info << std::endl;
                } else {
                    if (res.is_critical) { failed_critical++; std::cout << "  " << ui::RED << "✖ " << ui::RESET << ui::BOLD << res.tool_name << ui::RESET << " -> " << ui::RED << "NOT FOUND (CRITICAL)\n" << ui::RESET; }
                    else { std::cout << "  " << ui::YELLOW << "⚠ " << ui::RESET << ui::BOLD << res.tool_name << ui::RESET << " -> Optional (Not Installed)\n"; }
                }
            }
        }
    }
    
    std::cout << std::endl;

    if (failed_critical > 0) {
        ui::error("Comprehensive assessment complete. Total Critical Defects: " + std::to_string(failed_critical));
        return 1;
    }

    ui::success("All verified verification thresholds passed. System state secure.");
    return 0;
}

int UpdateCommand::run(IExecutionContext& ctx, const std::vector<std::string>& /*args*/) {
    std::cout << "Executing: update" << std::endl;
    return 0;
}

} // namespace nav::core
