#include "nav/core/deps.hpp"

#include "nav/core/cache.hpp"

#include <algorithm>
#include <fstream>
#include <sstream>
#include <vector>

namespace fs = std::filesystem;

namespace nav::core {

std::optional<fs::path> locked_cache_dir(const LockedPackage& lp,
                                         const fs::path& cache_root,
                                         const std::string& platform_key) {
    const std::string key = (lp.kind == PackageKind::Toolchain) ? platform_key : "source";
    auto it = lp.checksums.find(key);
    if (it == lp.checksums.end()) return std::nullopt;
    return package_dir(cache_root, lp.name, to_string(lp.version), it->second);
}

namespace {

// CMake list literal: each item double-quoted, space-separated, forward slashes.
void emit_path_list(std::ostringstream& os, const char* var,
                    const std::vector<fs::path>& items) {
    os << "set(" << var;
    for (const auto& p : items) os << " \"" << p.generic_string() << "\"";
    os << ")\n";
}

} // namespace

std::string render_deps_cmake(const Lockfile& lock, const fs::path& cache_root,
                              const std::string& platform_key,
                              const std::string& compiler_name) {
    std::vector<fs::path> include_dirs;
    std::vector<fs::path> link_dirs;
    std::vector<fs::path> libraries;
    fs::path compiler;

    std::error_code ec;
    // Deterministic order: lockfile packages are already name-sorted on load,
    // but sort defensively so the generated file is stable.
    std::vector<LockedPackage> pkgs = lock.packages;
    std::sort(pkgs.begin(), pkgs.end(),
              [](const LockedPackage& a, const LockedPackage& b) { return a.name < b.name; });

    for (const auto& lp : pkgs) {
        auto dir = locked_cache_dir(lp, cache_root, platform_key);
        if (!dir || !is_installed(*dir)) continue;

        if (lp.kind == PackageKind::Library) {
            const fs::path inc = *dir / "include";
            if (fs::is_directory(inc, ec)) include_dirs.push_back(inc);

            const fs::path lib = *dir / "lib";
            if (fs::is_directory(lib, ec)) {
                bool any_archive = false;
                std::vector<fs::path> archives;
                for (const auto& entry : fs::directory_iterator(lib, ec)) {
                    if (entry.path().extension() == ".a") {
                        archives.push_back(entry.path());
                        any_archive = true;
                    }
                }
                std::sort(archives.begin(), archives.end());
                for (auto& a : archives) libraries.push_back(a);
                if (any_archive) link_dirs.push_back(lib);
            }
        } else { // Toolchain
            if (!compiler_name.empty()) {
                const fs::path candidate = *dir / "bin" / compiler_name;
                if (fs::exists(candidate, ec)) compiler = candidate;
            }
        }
    }

    std::ostringstream os;
    os << "# Auto-generated by `nav build` from nav.lock + the package cache.\n";
    os << "# Do not edit; re-run `nav build` (or `nav fetch`) to regenerate.\n\n";
    emit_path_list(os, "NAV_DEPS_INCLUDE_DIRS", include_dirs);
    emit_path_list(os, "NAV_DEPS_LINK_DIRS", link_dirs);
    emit_path_list(os, "NAV_DEPS_LIBRARIES", libraries);
    os << "set(NAV_DEPS_COMPILER \"" << compiler.generic_string() << "\")\n";
    return os.str();
}

bool write_deps_cmake(const Lockfile& lock, const fs::path& cache_root,
                      const std::string& platform_key, const std::string& compiler_name,
                      const fs::path& out_path) {
    std::error_code ec;
    if (out_path.has_parent_path()) {
        fs::create_directories(out_path.parent_path(), ec);
        if (ec) return false;
    }
    std::ofstream f(out_path);
    if (!f) return false;
    f << render_deps_cmake(lock, cache_root, platform_key, compiler_name);
    return f.good();
}

} // namespace nav::core
