#include "nav/core/libdeps.hpp"

#include "nav/core/navhal.hpp"
#include "nav/core/ui.hpp"

#include <fstream>
#include <sstream>
#include <system_error>
#include <unordered_set>

namespace fs = std::filesystem;

namespace nav::core {

namespace {

// Depth-first resolver with cycle detection. Pushes each library in post-order
// (dependencies before dependents) into `out`, deduped by canonical name.
struct Resolver {
    IExecutionContext& ctx;
    std::vector<ResolvedLib>& out;
    std::unordered_set<std::string> done;      // fully resolved canonical names
    std::unordered_set<std::string> on_stack;  // cycle detection
    bool ok = true;

    // Resolve one dependency declared by the project rooted at `decl_root`.
    // Returns the canonical name, or nullopt on a hard error.
    std::optional<std::string> visit(const Dependency& dep, const fs::path& decl_root) {
        fs::path src;
        if (dep.is_path()) {
            std::error_code ec;
            src = fs::weakly_canonical(decl_root / dep.path, ec);
            if (ec) src = (decl_root / dep.path).lexically_normal();
            if (!fs::exists(src / "nav.toml", ec)) {
                ui::error("Dependency '" + dep.name + "': no nav.toml at " + src.string());
                ok = false;
                return std::nullopt;
            }
        } else { // git
            src = ensure_git_cached(ctx, dep.git, dep.ref);
            if (src.empty()) {
                ui::error("Dependency '" + dep.name + "': failed to fetch " + dep.git + ".");
                ok = false;
                return std::nullopt;
            }
        }

        auto depcfg = load_project_config(src);
        if (!depcfg) {
            ui::error("Dependency '" + dep.name + "': could not parse " + (src / "nav.toml").string());
            ok = false;
            return std::nullopt;
        }
        if (!depcfg->is_library()) {
            ui::error("Dependency '" + dep.name + "' (" + src.string() +
                      ") is not a library project (set [project].type = \"library\").");
            ok = false;
            return std::nullopt;
        }

        const std::string canonical = depcfg->project_name.empty() ? dep.name : depcfg->project_name;

        if (done.count(canonical)) return canonical; // already resolved elsewhere
        if (on_stack.count(canonical)) {
            ui::error("Dependency cycle detected at '" + canonical + "'.");
            ok = false;
            return std::nullopt;
        }

        on_stack.insert(canonical);
        std::vector<std::string> child_names;
        for (const auto& child : depcfg->dependencies) {
            auto cn = visit(child, src);
            if (!cn) { on_stack.erase(canonical); return std::nullopt; }
            child_names.push_back(*cn);
        }
        on_stack.erase(canonical);

        done.insert(canonical);
        out.push_back(ResolvedLib{canonical, src, std::move(child_names)});
        return canonical;
    }
};

// CMake path literal: forward slashes, quoted.
std::string q(const fs::path& p) { return "\"" + p.generic_string() + "\""; }

} // namespace

std::optional<std::vector<ResolvedLib>>
resolve_library_deps(IExecutionContext& ctx, const fs::path& root,
                     const ProjectConfig& cfg, std::vector<std::string>* out_direct) {
    std::vector<ResolvedLib> libs;
    Resolver r{ctx, libs};

    std::vector<std::string> direct;
    for (const auto& dep : cfg.dependencies) {
        auto name = r.visit(dep, root);
        if (!name) return std::nullopt;
        direct.push_back(*name);
    }
    if (!r.ok) return std::nullopt;
    if (out_direct) *out_direct = std::move(direct);
    return libs;
}

std::string render_libdeps_cmake(const std::vector<ResolvedLib>& libs,
                                 const std::vector<std::string>& direct) {
    std::ostringstream os;
    os << "# Auto-generated by `nav build` from nav.toml [dependencies].\n";
    os << "# Do not edit; re-run `nav build` to regenerate.\n\n";

    // Add every library subtree first (dependencies-first order), so later
    // target_link_libraries() edges can reference any of them.
    for (const auto& lib : libs) {
        os << "add_subdirectory(" << q(lib.src)
           << " \"${CMAKE_BINARY_DIR}/deps/" << lib.name << "\")\n";
    }
    os << "\n";

    // Wire inter-library edges (PUBLIC so headers propagate transitively).
    for (const auto& lib : libs) {
        for (const auto& child : lib.deps) {
            os << "target_link_libraries(" << lib.name << " PUBLIC " << child << ")\n";
        }
    }
    os << "\n";

    os << "set(NAV_DEP_TARGETS";
    for (const auto& d : direct) os << " " << d;
    os << ")\n";
    return os.str();
}

bool write_libdeps_cmake(const std::vector<ResolvedLib>& libs,
                         const std::vector<std::string>& direct,
                         const fs::path& out_path) {
    std::error_code ec;
    if (out_path.has_parent_path()) {
        fs::create_directories(out_path.parent_path(), ec);
        if (ec) return false;
    }
    std::ofstream f(out_path);
    if (!f) return false;
    f << render_libdeps_cmake(libs, direct);
    return f.good();
}

} // namespace nav::core
